### ISSUE TITLE
`Uncaught TypeError: storage.getItem is not a function` with create-react-app and polyfills

### ISSUE THREAD

**Issue by ryanberckmans** [Shopify/blockchain-components#16]
I'm trying out connect-wallet with vanilla setup and am receiving `Uncaught TypeError: storage.getItem is not a function` from redux-persist using create-react-app and polyfills for `Buffer` and `process`.

I'm using https://github.com/niksy/node-stdlib-browser for the polyfills.

Is this error related to a missing polyfill?

Do you have an example of connect-wallet in create-react-app?

**Comment by QuintonC** [comment]
Hey @ryanberckmans 👋 

I'm not certain what the cause of this error might be. My assumption might be similar to yours in that it is possibly a missing polyfill.

Would you be able to provide a sample app / repo that we can use for testing? If you could use a service like [CodeSandbox](https://codesandbox.io/) that would be great :) 

Not to dismiss the usage of Create React App, I do want to help resolve the issue, but I might recommend that if you're not set on using Create React App, it might be worthwhile to consider using more modern tooling such as [Vite](https://vitejs.dev/). 

Here is a [CodeSandbox](https://codesandbox.io/p/sandbox/shopify-connect-wallet-vite-example-9w7wv6) that uses Vite if you're interested in what that might look like.

**Comment by ryanberckmans** [comment]
Hey 👋 . I think you're right that I'd benefit from switching to something like Vite. I've been meaning to make the switch.

My create-react-app is fairly ordinary, except that I'm using a [fork](https://github.com/facebook/create-react-app/compare/main...ryanberckmans:create-react-app:main) of create-react-app for polyfills and tailwind support

```
  "react-scripts": "https://gitpkg.now.sh/ryanberckmans/create-react-app/packages/react-scripts?08746634d19a73958ba9b764b3cda418e1fce151",
```
I'll switch to Vite asap, and then try connect-wallet again. I'm looking forward to it, the library looks quite competitive, thanks for making it.
