### ISSUE TITLE
Is wallet address available on shopify webhooks?

### ISSUE THREAD

**Issue by aimproxy** [Shopify/blockchain-components#175]
Hey, I understand that Shopify is using the Ajax API to add the wallet address to the cart. However, I'm wondering what the purpose of this is. Shouldn't the wallet address be stored in the customer metafields instead? Additionally, I'm curious if the wallet address is available in Shopify webhooks such as orders/paid, checkout/created, and cart/created.

**Comment by jamiely** [comment]
> However, I'm wondering what the purpose of this is. 

The sole purpose of this is so that the wallet address is visible to the merchant when the cart attributes get copied to the order.

> Shouldn't the wallet address be stored in the customer metafields instead? 

Sure, that could be done. One reason we don't mention it is because it might make the component configuration more complex.

> Additionally, I'm curious if the wallet address is available in Shopify webhooks such as orders/paid, checkout/created, and cart/created.

The wallet address should be available in the order webhooks if you can obtain order attributes.

**Comment by aimproxy** [comment]
Hi @jamiely, thank you for responding so quickly. I may want to dig a little bit on that...

> Sure, that could be done by the implementor via custom callbacks. One reason we don't mention it is because it might make the component configuration more complex.

Do you know which API would be the most suitable to achieve this? The Ajax API doesn't have the customer object, and some of the Shopify functions are still in developer preview. I was considering using the Cart Transform API since it has the customer object, but it's only available in the developer preview bundles.

Also, what is the purpose of the @shopify/blockchain-components package? I know it has analytics, but what kind of analytics does it provide? Is Shopify planning to introduce new analytics features to the Admin?
