### ISSUE TITLE
MetaMask not showing on the Connect Wallet Modal

### ISSUE THREAD

**Issue by sunwrobert** [Shopify/blockchain-components#206]
<img width="430" alt="image" src="https://github.com/Shopify/blockchain-components/assets/6511174/2e6a3106-d680-4282-aee1-e211ada880e0">

Have been noticing that MM isn't available when I'm using the default connectors for the `connect-wallet`. Is this a known issue?

**Comment by QuintonC** [comment]
Hey there @sunwrobert 👋 

Thanks for dropping by! This definitely doesn't seem like something we've seen before.

Is MetaMask installed in your browser? If not, it won't when you are browsing on desktop. If you are on mobile you should see MetaMask.

Would you happen to have a sample repo I can take a look at for debugging? 

Looking forward to hearing back from you!

**Comment by sunwrobert** [comment]
oh, strangely it started showing up today. Might have been a conflict with my other wallet, Rabby, since that does do some things to make it take priority. 

And yeah, MetaMask was installed on my browser. If it pops up again, I'll let you know

**Comment by QuintonC** [comment]
Awesome, glad it worked itself out. If you're able to replicate the issue reliably please let me know!

My initial assumption would be that the other wallet you suggested might be conflicting with [this section](https://github.com/Shopify/blockchain-components/blob/ad9bf93c590e975b724c9519845fa21b2f8e2d60/packages/connect-wallet/src/utils/isInstalled.ts#L18-L26)
