### ISSUE TITLE
Conflicting peer dependencies

### ISSUE THREAD

**Issue by h4gen** [Shopify/blockchain-components#25]
Hi!

I don't know if I misunderstand smth. but it seems the components have version conflicts with their own dependencies:
```
.
├─┬ @shopify/connect-wallet 0.1.0
│ └─┬ siwe 1.1.6
│   └── ✕ unmet peer ethers@5.5.1: found 5.7.2
└─┬ @shopify/tokengate 0.1.0
  └─┬ @storybook/react 6.5.16
    └─┬ react-element-to-jsx-string 14.3.4
      ├── ✕ unmet peer react@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1": found 18.2.0 in @shopify/tokengate
      └── ✕ unmet peer react-dom@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1": found 18.2.0 in @shopify/tokengate
```

I am not able to create a clean install of `@shopify/connect-wallet` or `@shopify/tokengate` in the merchant facing app. Entry point is the [vanilla tokengating example app](https://github.com/Shopify/tokengating-example-app). I just bumped react to be compatible with `@shopify/tokengate`. I want to include them to build a gate preview as shown in [the docs](https://shopify.dev/docs/apps/blockchain/tokengating).

Thanks,
Hagen

**Comment by QuintonC** [comment]
Hey @h4gen 👋 

Out of curiosity, could you share which package manager you're using (npm, pnpm, yarn, etc.)? 

Aside from that it looks like we might have some additional dependency cleanup to resolve in our bundles (looking at the  `@storybook/react` error in the sample you provided).

If you're using **npm** could you remove `ethers` and `wagmi` from your package.json and try re-installing the `@shopify/connect-wallet` package?

If you're using **yarn** could you remove `ethers`, `wagmi`, and the `@shopify/connect-wallet` packages and re-run the install command with `yarn add @shopify/connect-wallet ethers wagmi`?

Another option that could be helpful is providing a reproducible sample via CodeSandbox of your application (if possible).

Thanks! 😄

**Comment by QuintonC** [comment]
Hey @h4gen, thanks for the response 🙂 

You'll notice that I've mentioned this issue in a pull request on the `tokengating-example-app` repository. It looks like there were conflicting dependencies even with NPM which https://github.com/Shopify/tokengating-example-app/pull/6 should resolve.

After that merges, can you try rebasing your example application and let me know if you're still experiencing peer dependency issues? Optionally, you can rebase prior to the pull request merging.
