### ISSUE TITLE
Build issue with nextJS

### ISSUE THREAD

**Issue by nichochar** [Shopify/blockchain-components#45]
Followed the instructions of the getting started, but couldn't get a nextJS app running (typescript)

I believe you should probably pin the versions of wagmi and ethers you're using, because they change a lot.

Error:
```
Error: Cannot find module '/Users/nicholascharriere/privy/shopify-connect/node_modules/ethers/lib/utils' imported from /Users/nicholascharriere/privy/shopify-connect/node_modules/@shopify/connect-wallet/dist/index.js
Did you mean to import ethers/lib/utils.js?
```

**Comment by QuintonC** [comment]
Hey @nichochar 👋 

We're currently working on resolving these issues with Webpack-based bundlers to resolve the ESM exported packages right now 😄

The issue related to ethers was resolved in #33

There are other related issues that are being resolved with these bundlers (here's a current list):
- #31 
- #33
- #34 
- #37 
- #44 

The latter of the two (#37 and #44) are to be merged here shortly, and then there are likely two more issues to resolve with the QueryClient for React Query + Wagmi as well as our state logger.

I'll keep this issue open and update you periodically as we work to resolve the issue 🙌

**Comment by nichochar** [comment]
Thanks for the quick response.
Indeed that ticket is exactly my issue. I also solved it with that modified import within the node modules and then ran into the other issue that PR describes with redux. Great minds 🧠.

Let me know if there is an alpha/beta version of the library I can use when the changes land. Appreciate it.

**Comment by QuintonC** [comment]
@nichochar You can test a snapshot version using the following versions:

```sh
yarn add @shopify/connect-wallet@0.0.0-snapshot-20230303202422
```
```sh
yarn add @shopify/gate-context-client@0.0.0-snapshot-20230303202422
```

If you don't mind, can you let us know if these work for you? Here is a [CodeSandbox repro](https://codesandbox.io/p/sandbox/elegant-silence-6bdexx?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A62%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A62%2C%22startLineNumber%22%3A13%7D%5D) if you need some help getting the package set up in Next. We're looking forward to hearing from you soon 😄

**Comment by nichochar** [comment]
Yes, it worked. This unblocks me as I'm in the prototyping phase. Thanks

**Comment by QuintonC** [comment]
> Yes, it worked. This unblocks me as I'm in the prototyping phase. Thanks

Nice! That's wonderful news.

Feel free to share your creation in the [discussions show and tell category](https://github.com/Shopify/blockchain-components/discussions/categories/show-and-tell). We're looking forward to seeing what you create 😄 

I'm going to go ahead and close this issue. Please feel free to re-open it if you need anything additional support or feel free to open another 🙌
